name: github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  id-token: write
  pages: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish Monitor/Monitor.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

      - name: Rename .dll to .bin and update blazor.boot.json
        run: |
          for file in dist/Web/wwwroot/_framework/*.dll; do
            mv "$file" "${file%.dll}.bin"
          done
          sed -i 's/\.dll"/.bin"/g' dist/Web/wwwroot/_framework/blazor.boot.json
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/Web/wwwroot'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
